backend:
  name: github
  repo: MussadiqKhan/wallbrook
  #repo: ali-baker/huss-gatsby
media_folder: "src/images"
public_folder: "/images"
media_folder_relative: true

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Wholesale"
        name: "wholesale"
        file: "src/markdown-pages/wholesale.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: markdown }
          - {
              label: "Featured Image",
              name: "thumbnail",
              widget: "image",
              default: "wholesale.png",
            }
          - { label: Second Section Title, name: title2, widget: string }
          - { label: Second Section SubTitle, name: subtitle2, widget: text }
          - { label: Contact Section Title, name: contacttitle, widget: string }
          - { label: E-mail, name: email, widget: string }
          - { label: Contact, name: contact, widget: string }
          - label: "Table data"
            name: "listitems"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "text" }
      - label: "About Page"
        name: "About Page"
        file: "src/markdown-pages/about.md"
        fields:
          - { label: Main Title, name: title, widget: string }
          - { label: SubTitle, name: subtitle, widget: text }
          - { label: Button Text, name: buttontext, widget: string }
          - { label: Button Email, name: buttonemail, widget: string }
          - { label: Title Section 1, name: careertitle, widget: string }
          - {
              label: Description Section 1,
              name: careerdescription,
              widget: string,
            }
          - { label: Title Section 2, name: lifetitle, widget: string }
          - {
              label: Description Section 2,
              name: lifedescription,
              widget: string,
            }
          - {
              label: "Featured Image",
              name: "thumbnail",
              widget: "image",
              default: "wholesale.png",
            }
          - {
              label: "Featured Image",
              name: "thumbnail",
              widget: "image",
              default: "wholesale.png",
            }
      - label: "Advisory Page"
        name: "Advisory Page"
        file: "src/markdown-pages/advisory.md"
        fields:
          - { label: Main Title, name: title, widget: string }
          - { label: SubTitle, name: subtitle, widget: text }
          - { label: FAQ1, name: FAQ1, widget: string }
          - { label: FAQ1 Answer, name: answer1, widget: text }
          - { label: FAQ2, name: FAQ2, widget: string }
          - { label: FAQ2 Answer, name: answer2, widget: text }
          - { label: FAQ3, name: FAQ3, widget: string }
          - { label: FAQ3 Answer, name: answer3, widget: text }
          - { label: FAQ4, name: FAQ4, widget: string }
          - { label: FAQ4 Answer, name: answer4, widget: text }
          - { label: Contact Title, name: contacttitle, widget: string }
          - { label: Contact Desc, name: contactdesc, widget: text }
          - {
              label: "Featured Image",
              name: "thumbnail",
              widget: "image",
              default: "wholesale.png",
            }
      - label: "Help Page"
        name: "Help Page"
        file: "src/markdown-pages/help.md"
        fields:
          - { label: Main Title, name: title, widget: string }
          - { label: SubTitle, name: subtitle, widget: text }
          - { label: First Help Title, name: helptitle1, widget: string }
          - label: "Help data 1"
            name: "helplist1"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
          - { label: Second Help Title, name: helptitle2, widget: string }
          - label: "Help data 2"
            name: "helplist2"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
          - { label: Third Help Title, name: helptitle3, widget: string }
          - label: "Help data 3"
            name: "helplist3"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
          - { label: Fourth Help Title, name: helptitle4, widget: string }
          - label: "Help data 4"
            name: "helplist4"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
          - { label: Fifth Help Title, name: helptitle5, widget: string }
          - label: "Help data 5"
            name: "helplist5"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
          - { label: Sixth Help Title, name: helptitle6, widget: string }
          - label: "Help data 6"
            name: "helplist6"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "text" }
          - { label: Helo Main, name: helpmain, widget: string }
          - { label: Help Section 1, name: help1, widget: string }
          - { label: Help Desc 1, name: helpdesc1, widget: text }
          - { label: Help Section 2, name: help2, widget: string }
          - { label: Help Desc 2, name: helpdesc2, widget: text }
          - { label: Help Section 3, name: help3, widget: string }
          - { label: Help Desc 3, name: helpdesc3, widget: text }
          - { label: Help Section 4, name: help4, widget: string }
          - { label: Help Desc 4, name: helpdesc4, widget: text }
          - { label: Contact Title, name: contacttitle, widget: string }
          - { label: Contact Desc, name: contactdesc, widget: string }
          - {
              label: "Featured Image",
              name: "thumbnail",
              widget: "image",
              default: "wholesale.png",
            }
